### PR TITLE
Update message.h

### PR DESCRIPTION
**Pull request by dpirly**
fix an typo of  macro definition

### CODE REVIEW

**Comment by lundmar** [comment]
Thanks 👍

**Comment by lundmar** [comment]
FYI - the library is still in very early development. I expect to add a lot of changes in the near future so we can have basic hislip up and running 😄

**Comment by dpirly** [comment]
By coincidence, I also have a DC Power Supply project , and wants to use this library 👍

**Comment by lundmar** [comment]
Great - feel free to continue contributing if you would like to help. However, it might be wise to hold off for a little bit until I get the basics sorted out. The current code base is subject to a lot of changes that I hope to add within the next couple of weeks to get a somewhat functional implementation that can bring it out of pre-alpha and into alpha 😄

**Comment by dpirly** [comment]
Ok, Thanks for the advice. 😄

**Pull request merged**
